### ISSUE TITLE
How to use with ES6 arrow function

### ISSUE THREAD

**Issue by charandas** [bornkiller/rollup-plugin-ng-annotate#1]
Hey @bornkiller, I am curious how to use this with ES6 arrow functions.

The AngularClass repo [here](https://github.com/AngularClass/NG6-starter) uses Webpack and does it like so:
```
.config(($locationProvider) => {
  "ngInject";
  // @see: https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions
  // #how-to-configure-your-server-to-work-with-html5mode
  $locationProvider.html5Mode(true).hashPrefix('!');
});
```

Is there a way to use it using rollup with your plugin?

**Comment by huang-xiao-jian** [comment]
the repo is deprecated, just use babel.
