### ISSUE TITLE
Sourcemaps being left empty

### ISSUE THREAD

**Issue by charandas** [bornkiller/rollup-plugin-ng-annotate#2]
@bornkiller I love this plugin as it essentially gets me annotations in a very simple manner.

However, I lose on `sourceMaps`. I am not an expert, but if you direct me with some guidance, perhaps I could contribute a PR.

Let me know.

**Comment by mtrias** [comment]
@charandas were you able to address this in your project?

**Comment by charandas** [comment]
@mtrias I turned to this Babel plugin which I use with jspm currently.

https://www.npmjs.com/package/babel-plugin-angularjs-annotate

**Comment by mtrias** [comment]
Ok, thanks !
